name: Capstone Project FE

# Run the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js environment

      - name: Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      # Install dependencies and build using npm

      - name: Install Dependencies
        run: npm install

      - name: Build the project
        run: npm run build

        # Optionally, you can run tests
      - name: Run tests
        run: npm test  # Or 'yarn test' if applicable