name: Capstone Project FE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build

  check-merge-conflicts:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check for merge conflicts
        run: |
          git fetch origin main
          if git merge --no-commit --no-ff --allow-unrelated-histories origin/main; then
            echo "No merge conflicts."
            git merge --abort  # Abort the merge if there are no conflicts
          else
            echo "Merge conflicts detected!"
            exit 1  # Fail the job if there are merge conflicts
          fi

